version: "3.9"

services:
  db:
    image: "postgres"
    environment:
      POSTGRES_USER: "city"
      POSTGRES_PASSWORD: "citylinktuc"
      POSTGRES_DB: "citylink"
    ports:
      - '5432:5432'

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      NODE_ENV: production
    command: npm start
    volumes:
      - /app/node_modules
      - ./client:/app

  server:
    build: ./server
    ports:
      - '8000:8000'
    environment:
      DATABASE_URL: "postgresql://city:citylinktuc@db:5432/citylink?schema=public"
      JWT_SECRET: "citylinktucsecret"
      PORT: 8000
    depends_on:
      - db
